Daily Commit
오류_
HTTP Status 500 - Request processing failed; nested exception is
org.springframework.dao.DataIntegrityViolationException:

type Exception report

message Request processing failed; nested exception is
org.springframework.dao.DataIntegrityViolationException:

description The server encountered an internal error that prevented it
from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing
failed; nested exception is
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause:
java.sql.SQLIntegrityConstraintViolationException: ORA-02292: integrity
constraint (GOLDSTAR.SYS_C007509) violated - child record found

### The error may involve companymember.delete-Inline
### The error occurred while setting parameters
### SQL: delete from CompanyMember   where companyID = ?
### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-02292:
integrity constraint (GOLDSTAR.SYS_C007509) violated - child record
found

; SQL []; ORA-02292: integrity constraint (GOLDSTAR.SYS_C007509)
violated - child record found
; nested exception is java.sql.SQLIntegrityConstraintViolationException:
ORA-02292: integrity constraint (GOLDSTAR.SYS_C007509) violated - child
record found

	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause:
java.sql.SQLIntegrityConstraintViolationException: ORA-02292: integrity
constraint (GOLDSTAR.SYS_C007509) violated - child record found

### The error may involve companymember.delete-Inline
### The error occurred while setting parameters
### SQL: delete from CompanyMember   where companyID = ?
### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-02292:
integrity constraint (GOLDSTAR.SYS_C007509) violated - child record
found

; SQL []; ORA-02292: integrity constraint (GOLDSTAR.SYS_C007509)
violated - child record found
; nested exception is java.sql.SQLIntegrityConstraintViolationException:
ORA-02292: integrity constraint (GOLDSTAR.SYS_C007509) violated - child
record found

	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:71)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:364)
	com.sun.proxy.$Proxy28.delete(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:264)
	spring.model.companymember.CompanyMemberDAO.delete(CompanyMemberDAO.java:112)
	spring.sts.kb.CompanyMemberController.delete(CompanyMemberController.java:61)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:497)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

java.sql.SQLIntegrityConstraintViolationException: ORA-02292: integrity
constraint (GOLDSTAR.SYS_C007509) violated - child record found

	oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:85)
	oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133)
	oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:206)
	oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
	oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
	oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1034)
	oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:194)
	oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:953)
	oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1222)
	oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3387)
	oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3488)
	oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1374)
	org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
	org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:161)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:497)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:354)
	com.sun.proxy.$Proxy28.delete(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:264)
	spring.model.companymember.CompanyMemberDAO.delete(CompanyMemberDAO.java:112)
	spring.sts.kb.CompanyMemberController.delete(CompanyMemberController.java:61)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:497)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
note The full stack trace of the root cause is available in the Apache
Tomcat/8.0.33 logs.

Apache Tomcat/8.0.33